using Microsoft.AspNetCore.Mvc.Razor;
using Nop.Core;
using Nop.Core.Data;
using Nop.Core.Infrastructure;
using Nop.Services.Localization;
using Nop.Web.Framework.Localization;
using Nop.Web.Framework.Themes;

namespace Nop.Web.Framework.ViewEngines.Razor
{
    /// <summary>
    /// Web view page
    /// </summary>
    /// <typeparam name="TModel">Model</typeparam>
    /// <remarks>
    /// Ported from <c>System.Web.Mvc.WebViewPage&lt;TModel&gt;</c> to
    /// <see cref="RazorPage{TModel}"/> (task 6.3, Requirement 4.4). The class stays
    /// <c>abstract</c>, so <see cref="RazorPageBase.ExecuteAsync"/> — which is abstract on the
    /// ASP.NET Core base and is generated by the Razor compiler for each concrete
    /// <c>.cshtml</c> — does not have to be overridden here.
    /// </remarks>
    public abstract class WebViewPage<TModel> : RazorPage<TModel>
    {
        private ILocalizationService _localizationService;
        private Localizer _localizer;

        /// <summary>
        /// Get a localized resources
        /// </summary>
        public Localizer T
        {
            get
            {
                if (_localizer == null)
                {
                    //null localizer
                    //_localizer = (format, args) => new LocalizedString((args == null || args.Length == 0) ? format : string.Format(format, args));

                    //default localizer
                    _localizer = (format, args) =>
                                     {
                                         var resFormat = GetLocalizationService()?.GetResource(format);
                                         if (string.IsNullOrEmpty(resFormat))
                                         {
                                             return new LocalizedString(format);
                                         }
                                         return
                                             new LocalizedString((args == null || args.Length == 0)
                                                                     ? resFormat
                                                                     : string.Format(resFormat, args));
                                     };
                }
                return _localizer;
            }
        }

        /// <summary>
        /// Resolve the localization service, or <c>null</c> while the database is not installed.
        /// </summary>
        /// <remarks>
        /// Replaces the 3.90 <c>InitHelpers()</c> override. <c>InitHelpers</c> was a
        /// <c>System.Web.WebPages.WebPageBase</c> lifecycle hook that ASP.NET Core's
        /// <see cref="RazorPageBase"/> does not have — there is no per-page initialization
        /// callback at all, so the resolve moved to first use.
        /// </remarks>
        protected virtual ILocalizationService GetLocalizationService()
        {
            if (_localizationService == null && DataSettingsHelper.DatabaseIsInstalled())
                _localizationService = EngineContext.Current.Resolve<ILocalizationService>();

            return _localizationService;
        }

        /// <summary>
        /// Return a value indicating whether the working language and theme support RTL (right-to-left)
        /// </summary>
        /// <returns></returns>
        public bool ShouldUseRtlTheme()
        {
            var workContext = EngineContext.Current.Resolve<IWorkContext>();
            var supportRtl = workContext.WorkingLanguage.Rtl;
            if (supportRtl)
            {
                //ensure that the active theme also supports it
                var themeProvider = EngineContext.Current.Resolve<IThemeProvider>();
                var themeContext = EngineContext.Current.Resolve<IThemeContext>();
                supportRtl = themeProvider.GetThemeConfiguration(themeContext.WorkingThemeName).SupportRtl;
            }
            return supportRtl;
        }
    }

    /// <summary>
    /// Web view page
    /// </summary>
    public abstract class WebViewPage : WebViewPage<dynamic>
    {
    }
}
