//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Nop.Plugin.Shipping.UPS.track {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    //
    // TASK 14.5: the generated TrackService proxy that USED to sit here derived from
    // System.Web.Services.Protocols.SoapHttpClientProtocol, which has no net10.0 counterpart.
    // Following the 4.2 precedent (EU VAT ASMX proxy replaced by hand-built SOAP over HttpClient)
    // and the 14.3 FedEx port, ONLY the proxy class was replaced - by the hand-built TrackService
    // in TrackService.cs, which preserves the parameterless ctor, the UPSSecurityValue property and
    // the ProcessTrack(TrackRequest) method, plus the exact SOAP 1.1 / document-literal-bare wire
    // shape the generated proxy sent. UNLIKE FedEx, UPS sends UPSSecurity as a SOAP HEADER
    // ([SoapHeader("UPSSecurityValue")]): the invoker serializes it into <soap:Header>. SOAP action
    // "http://onlinetools.ups.com/webservices/TrackBinding/v2.0", body element "TrackRequest"
    // (ns http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0), reply "TrackResponse", header UPSSecurity
    // (ns http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0). Every DTO below is KEPT verbatim; the
    // async machinery was removed as unused. See UpsSoapInvoker.cs.
    //
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable=false)]
    //TASK 14.5: base was System.Web.Services.Protocols.SoapHeader (no net10.0 counterpart). It is
    //a plain [XmlRoot]/[XmlType] type, so dropping the base changes nothing about how it serializes
    //into <soap:Header> - UpsSoapInvoker writes it there explicitly.
    public partial class UPSSecurity {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
            }
        }
        
        /// <remarks/>
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class MessageType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class StatusType {
        
        private string typeField;
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class TransportFacilityType {
        
        private string typeField;
        
        private string codeField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ActivityLocationType {
        
        private AddressType addressField;
        
        private TransportFacilityType transportFacilityField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string signedForByNameField;
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public TransportFacilityType TransportFacility {
            get {
                return this.transportFacilityField;
            }
            set {
                this.transportFacilityField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SignedForByName {
            get {
                return this.signedForByNameField;
            }
            set {
                this.signedForByNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AddressType {
        
        private string[] addressLineField;
        
        private string cityField;
        
        private string stateProvinceCodeField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceCode {
            get {
                return this.stateProvinceCodeField;
            }
            set {
                this.stateProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AlternateTrackingInfoType {
        
        private string typeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ActivityType {
        
        private AlternateTrackingInfoType[] alternateTrackingInfoField;
        
        private ActivityLocationType activityLocationField;
        
        private StatusType statusField;
        
        private string dateField;
        
        private string timeField;
        
        private DocumentType[] documentField;
        
        private AdditionalCodeDescriptionValueType[] additionalAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternateTrackingInfo")]
        public AlternateTrackingInfoType[] AlternateTrackingInfo {
            get {
                return this.alternateTrackingInfoField;
            }
            set {
                this.alternateTrackingInfoField = value;
            }
        }
        
        /// <remarks/>
        public ActivityLocationType ActivityLocation {
            get {
                return this.activityLocationField;
            }
            set {
                this.activityLocationField = value;
            }
        }
        
        /// <remarks/>
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Document")]
        public DocumentType[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAttribute")]
        public AdditionalCodeDescriptionValueType[] AdditionalAttribute {
            get {
                return this.additionalAttributeField;
            }
            set {
                this.additionalAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class DocumentType {
        
        private CommonCodeDescriptionType typeField;
        
        private string contentField;
        
        private CommonCodeDescriptionType formatField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public CommonCodeDescriptionType Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class CommonCodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AdditionalCodeDescriptionValueType {
        
        private string codeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class PackageAddressType {
        
        private CommonCodeDescriptionType typeField;
        
        private AddressType addressField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class PackageType {
        
        private string trackingNumberField;
        
        private DeliveryDetailType[] deliveryDetailField;
        
        private PackageAddressType[] packageAddressField;
        
        private ServiceOptionType[] packageServiceOptionField;
        
        private CODType cODField;
        
        private ActivityType[] activityField;
        
        private MessageType[] messageField;
        
        private WeightType packageWeightField;
        
        private ReferenceNumberType[] referenceNumberField;
        
        private string[] alternateTrackingNumberField;
        
        private AlternateTrackingInfoType[] alternateTrackingInfoField;
        
        private DocumentType[] documentField;
        
        private AdditionalCodeDescriptionValueType[] additionalAttributeField;
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryDetail")]
        public DeliveryDetailType[] DeliveryDetail {
            get {
                return this.deliveryDetailField;
            }
            set {
                this.deliveryDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageAddress")]
        public PackageAddressType[] PackageAddress {
            get {
                return this.packageAddressField;
            }
            set {
                this.packageAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageServiceOption")]
        public ServiceOptionType[] PackageServiceOption {
            get {
                return this.packageServiceOptionField;
            }
            set {
                this.packageServiceOptionField = value;
            }
        }
        
        /// <remarks/>
        public CODType COD {
            get {
                return this.cODField;
            }
            set {
                this.cODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity")]
        public ActivityType[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message")]
        public MessageType[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public WeightType PackageWeight {
            get {
                return this.packageWeightField;
            }
            set {
                this.packageWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceNumber")]
        public ReferenceNumberType[] ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternateTrackingNumber")]
        public string[] AlternateTrackingNumber {
            get {
                return this.alternateTrackingNumberField;
            }
            set {
                this.alternateTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternateTrackingInfo")]
        public AlternateTrackingInfoType[] AlternateTrackingInfo {
            get {
                return this.alternateTrackingInfoField;
            }
            set {
                this.alternateTrackingInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Document")]
        public DocumentType[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAttribute")]
        public AdditionalCodeDescriptionValueType[] AdditionalAttribute {
            get {
                return this.additionalAttributeField;
            }
            set {
                this.additionalAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class DeliveryDetailType {
        
        private CommonCodeDescriptionType typeField;
        
        private string dateField;
        
        private string timeField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ServiceOptionType {
        
        private CommonCodeDescriptionType typeField;
        
        private string valueField;
        
        private AdditionalCodeDescriptionValueType[] additionalAttributeField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAttribute")]
        public AdditionalCodeDescriptionValueType[] AdditionalAttribute {
            get {
                return this.additionalAttributeField;
            }
            set {
                this.additionalAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class CODType {
        
        private AmountType amountField;
        
        private CODStatusType statusField;
        
        private string controlNumberField;
        
        /// <remarks/>
        public AmountType Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public CODStatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ControlNumber {
            get {
                return this.controlNumberField;
            }
            set {
                this.controlNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AmountType {
        
        private string currencyCodeField;
        
        private string monetaryValueField;
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MonetaryValue {
            get {
                return this.monetaryValueField;
            }
            set {
                this.monetaryValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class CODStatusType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class WeightType {
        
        private UnitOfMeasurementType unitOfMeasurementField;
        
        private string weightField;
        
        /// <remarks/>
        public UnitOfMeasurementType UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class UnitOfMeasurementType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ReferenceNumberType {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AppointmentType {
        
        private DateTimeType madeField;
        
        private DateTimeType requestedField;
        
        private string beginTimeField;
        
        private string endTimeField;
        
        /// <remarks/>
        public DateTimeType Made {
            get {
                return this.madeField;
            }
            set {
                this.madeField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType Requested {
            get {
                return this.requestedField;
            }
            set {
                this.requestedField = value;
            }
        }
        
        /// <remarks/>
        public string BeginTime {
            get {
                return this.beginTimeField;
            }
            set {
                this.beginTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class DateTimeType {
        
        private string dateField;
        
        private string timeField;
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class CarrierActivityInformationType {
        
        private string carrierIdField;
        
        private string descriptionField;
        
        private string statusField;
        
        private DateTimeType arrivalField;
        
        private DateTimeType departureField;
        
        private string originPortField;
        
        private string destinationPortField;
        
        /// <remarks/>
        public string CarrierId {
            get {
                return this.carrierIdField;
            }
            set {
                this.carrierIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType Arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType Departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
            }
        }
        
        /// <remarks/>
        public string OriginPort {
            get {
                return this.originPortField;
            }
            set {
                this.originPortField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationPort {
            get {
                return this.destinationPortField;
            }
            set {
                this.destinationPortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class DestinationPortDetailType {
        
        private string destinationPortField;
        
        private DateTimeType estimatedArrivalField;
        
        /// <remarks/>
        public string DestinationPort {
            get {
                return this.destinationPortField;
            }
            set {
                this.destinationPortField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType EstimatedArrival {
            get {
                return this.estimatedArrivalField;
            }
            set {
                this.estimatedArrivalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class OriginPortDetailType {
        
        private string originPortField;
        
        private DateTimeType estimatedDepartureField;
        
        /// <remarks/>
        public string OriginPort {
            get {
                return this.originPortField;
            }
            set {
                this.originPortField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType EstimatedDeparture {
            get {
                return this.estimatedDepartureField;
            }
            set {
                this.estimatedDepartureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipmentActivityType {
        
        private AddressType activityLocationField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string dateField;
        
        private string timeField;
        
        private string trailerField;
        
        private DocumentType[] documentField;
        
        private AdditionalCodeDescriptionValueType[] additionalAttributeField;
        
        /// <remarks/>
        public AddressType ActivityLocation {
            get {
                return this.activityLocationField;
            }
            set {
                this.activityLocationField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Trailer {
            get {
                return this.trailerField;
            }
            set {
                this.trailerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Document")]
        public DocumentType[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAttribute")]
        public AdditionalCodeDescriptionValueType[] AdditionalAttribute {
            get {
                return this.additionalAttributeField;
            }
            set {
                this.additionalAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class NumberOfPackagingUnitType {
        
        private CommonCodeDescriptionType typeField;
        
        private string valueField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class VolumeType {
        
        private UnitOfMeasurementType unitOfMeasurementField;
        
        private string valueField;
        
        /// <remarks/>
        public UnitOfMeasurementType UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ServiceCenterType {
        
        private CommonCodeDescriptionType typeField;
        
        private string nameField;
        
        private AddressType addressField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipmentReferenceNumberType {
        
        private string codeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ServiceType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipmentAddressType {
        
        private CommonCodeDescriptionType typeField;
        
        private AddressType addressField;
        
        /// <remarks/>
        public CommonCodeDescriptionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class CodeDescriptionValueType {
        
        private string codeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipmentType {
        
        private CodeDescriptionValueType inquiryNumberField;
        
        private RefShipmentType shipmentType1Field;
        
        private string candidateBookmarkField;
        
        private string shipperNumberField;
        
        private ShipmentAddressType[] shipmentAddressField;
        
        private WeightType shipmentWeightField;
        
        private ServiceType serviceField;
        
        private ShipmentReferenceNumberType[] referenceNumberField;
        
        private CommonCodeDescriptionType currentStatusField;
        
        private string pickupDateField;
        
        private ServiceCenterType[] serviceCenterField;
        
        private DeliveryDetailType[] deliveryDetailField;
        
        private VolumeType volumeField;
        
        private string billToNameField;
        
        private NumberOfPackagingUnitType[] numberOfPackagingUnitField;
        
        private ServiceOptionType[] shipmentServiceOptionField;
        
        private CODType cODField;
        
        private string signedForByNameField;
        
        private ShipmentActivityType[] activityField;
        
        private OriginPortDetailType originPortDetailField;
        
        private DestinationPortDetailType destinationPortDetailField;
        
        private string descriptionOfGoodsField;
        
        private DateTimeType cargoReadyField;
        
        private DateTimeType manifestField;
        
        private CarrierActivityInformationType[] carrierActivityInformationField;
        
        private DocumentType[] documentField;
        
        private string fileNumberField;
        
        private AppointmentType appointmentField;
        
        private PackageType[] packageField;
        
        private AdditionalCodeDescriptionValueType[] additionalAttributeField;
        
        /// <remarks/>
        public CodeDescriptionValueType InquiryNumber {
            get {
                return this.inquiryNumberField;
            }
            set {
                this.inquiryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentType")]
        public RefShipmentType ShipmentType1 {
            get {
                return this.shipmentType1Field;
            }
            set {
                this.shipmentType1Field = value;
            }
        }
        
        /// <remarks/>
        public string CandidateBookmark {
            get {
                return this.candidateBookmarkField;
            }
            set {
                this.candidateBookmarkField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentAddress")]
        public ShipmentAddressType[] ShipmentAddress {
            get {
                return this.shipmentAddressField;
            }
            set {
                this.shipmentAddressField = value;
            }
        }
        
        /// <remarks/>
        public WeightType ShipmentWeight {
            get {
                return this.shipmentWeightField;
            }
            set {
                this.shipmentWeightField = value;
            }
        }
        
        /// <remarks/>
        public ServiceType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceNumber")]
        public ShipmentReferenceNumberType[] ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public CommonCodeDescriptionType CurrentStatus {
            get {
                return this.currentStatusField;
            }
            set {
                this.currentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceCenter")]
        public ServiceCenterType[] ServiceCenter {
            get {
                return this.serviceCenterField;
            }
            set {
                this.serviceCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryDetail")]
        public DeliveryDetailType[] DeliveryDetail {
            get {
                return this.deliveryDetailField;
            }
            set {
                this.deliveryDetailField = value;
            }
        }
        
        /// <remarks/>
        public VolumeType Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string BillToName {
            get {
                return this.billToNameField;
            }
            set {
                this.billToNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NumberOfPackagingUnit")]
        public NumberOfPackagingUnitType[] NumberOfPackagingUnit {
            get {
                return this.numberOfPackagingUnitField;
            }
            set {
                this.numberOfPackagingUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentServiceOption")]
        public ServiceOptionType[] ShipmentServiceOption {
            get {
                return this.shipmentServiceOptionField;
            }
            set {
                this.shipmentServiceOptionField = value;
            }
        }
        
        /// <remarks/>
        public CODType COD {
            get {
                return this.cODField;
            }
            set {
                this.cODField = value;
            }
        }
        
        /// <remarks/>
        public string SignedForByName {
            get {
                return this.signedForByNameField;
            }
            set {
                this.signedForByNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity")]
        public ShipmentActivityType[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        public OriginPortDetailType OriginPortDetail {
            get {
                return this.originPortDetailField;
            }
            set {
                this.originPortDetailField = value;
            }
        }
        
        /// <remarks/>
        public DestinationPortDetailType DestinationPortDetail {
            get {
                return this.destinationPortDetailField;
            }
            set {
                this.destinationPortDetailField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionOfGoods {
            get {
                return this.descriptionOfGoodsField;
            }
            set {
                this.descriptionOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType CargoReady {
            get {
                return this.cargoReadyField;
            }
            set {
                this.cargoReadyField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeType Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CarrierActivityInformation")]
        public CarrierActivityInformationType[] CarrierActivityInformation {
            get {
                return this.carrierActivityInformationField;
            }
            set {
                this.carrierActivityInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Document")]
        public DocumentType[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public string FileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
            }
        }
        
        /// <remarks/>
        public AppointmentType Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Package")]
        public PackageType[] Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAttribute")]
        public AdditionalCodeDescriptionValueType[] AdditionalAttribute {
            get {
                return this.additionalAttributeField;
            }
            set {
                this.additionalAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class RefShipmentType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType {
        
        private CodeDescriptionType responseStatusField;
        
        private CodeDescriptionType[] alertField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        public CodeDescriptionType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public CodeDescriptionType[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipperAccountInfoType {
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipToRequestType {
        
        private AddressRequestType addressField;
        
        /// <remarks/>
        public AddressRequestType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class AddressRequestType {
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class ShipFromRequestType {
        
        private AddressRequestType addressField;
        
        /// <remarks/>
        public AddressRequestType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class PickupDateRangeType {
        
        private string beginDateField;
        
        private string endDateField;
        
        /// <remarks/>
        public string BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType {
        
        private string[] requestOptionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption")]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class TrackRequest {
        
        private RequestType requestField;
        
        private string inquiryNumberField;
        
        private string trackingOptionField;
        
        private string candidateBookmarkField;
        
        private ReferenceNumberType referenceNumberField;
        
        private PickupDateRangeType pickupDateRangeField;
        
        private string shipperNumberField;
        
        private ShipFromRequestType shipFromField;
        
        private ShipToRequestType shipToField;
        
        private RefShipmentType shipmentTypeField;
        
        private ShipperAccountInfoType shipperAccountInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string InquiryNumber {
            get {
                return this.inquiryNumberField;
            }
            set {
                this.inquiryNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingOption {
            get {
                return this.trackingOptionField;
            }
            set {
                this.trackingOptionField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateBookmark {
            get {
                return this.candidateBookmarkField;
            }
            set {
                this.candidateBookmarkField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceNumberType ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public PickupDateRangeType PickupDateRange {
            get {
                return this.pickupDateRangeField;
            }
            set {
                this.pickupDateRangeField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
        
        /// <remarks/>
        public ShipFromRequestType ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        public ShipToRequestType ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public RefShipmentType ShipmentType {
            get {
                return this.shipmentTypeField;
            }
            set {
                this.shipmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public ShipperAccountInfoType ShipperAccountInfo {
            get {
                return this.shipperAccountInfoField;
            }
            set {
                this.shipperAccountInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")]
    public partial class TrackResponse {
        
        private ResponseType responseField;
        
        private ShipmentType[] shipmentField;
        
        private string[] disclaimerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shipment")]
        public ShipmentType[] Shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Disclaimer")]
        public string[] Disclaimer {
            get {
                return this.disclaimerField;
            }
            set {
                this.disclaimerField = value;
            }
        }
    }
}

#pragma warning restore 1591