//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Replaced System.Configuration.ApplicationSettingsBase with a simple static class for .NET 10.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Services.Properties {
    
    internal sealed partial class Settings {
        
        private static readonly Settings defaultInstance = new Settings();
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        public string Nop_Services_EuropaCheckVatService_checkVatService {
            get {
                return "http://ec.europa.eu/taxation_customs/vies/services/checkVatService";
            }
        }
    }
}
