// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// Rewritten for .NET Core/5+ to use HttpClient instead of System.Web.Services.
// Original modifications by Chris Trottier.

using System;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Xml;
using System.Xml.Serialization;

namespace Nop.Plugin.Shipping.Fedex.TrackServiceReference
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public partial class TrackService : IDisposable
    {
        private readonly HttpClient _httpClient;
        private readonly string _url;

        /// <remarks/>
        public TrackService(string Url)
        {
            _url = Url;
            _httpClient = new HttpClient();
        }

        /// <remarks/>
        public TrackReply track(TrackRequest TrackRequest)
        {
            string soapEnvelope = BuildSoapEnvelope("track", TrackRequest, "http://fedex.com/ws/track/v5");
            var content = new StringContent(soapEnvelope, Encoding.UTF8, "text/xml");
            content.Headers.Add("SOAPAction", "track");

            var response = _httpClient.PostAsync(_url, content).GetAwaiter().GetResult();
            response.EnsureSuccessStatusCode();

            var responseContent = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            return DeserializeSoapResponse<TrackReply>(responseContent, "TrackReply", "http://fedex.com/ws/track/v5");
        }

        private string BuildSoapEnvelope<T>(string operationName, T request, string ns)
        {
            var serializer = new XmlSerializer(typeof(T), ns);
            var sb = new StringBuilder();
            using (var writer = new StringWriter(sb))
            {
                serializer.Serialize(writer, request);
            }

            // Extract the inner XML (without the XML declaration)
            var requestXml = sb.ToString();
            var doc = new XmlDocument();
            doc.LoadXml(requestXml);
            var innerXml = doc.DocumentElement.OuterXml;

            return $@"<?xml version=""1.0"" encoding=""utf-8""?>
<soap:Envelope xmlns:soap=""http://schemas.xmlsoap.org/soap/envelope/"">
  <soap:Body>
    {innerXml}
  </soap:Body>
</soap:Envelope>";
        }

        private T DeserializeSoapResponse<T>(string soapResponse, string elementName, string ns)
        {
            var doc = new XmlDocument();
            doc.LoadXml(soapResponse);

            var nsMgr = new XmlNamespaceManager(doc.NameTable);
            nsMgr.AddNamespace("v5", ns);
            nsMgr.AddNamespace("soap", "http://schemas.xmlsoap.org/soap/envelope/");

            var node = doc.SelectSingleNode($"//v5:{elementName}", nsMgr);
            if (node == null)
            {
                // Try without namespace
                node = doc.SelectSingleNode($"//*[local-name()='{elementName}']");
            }

            if (node == null)
                throw new InvalidOperationException($"Could not find {elementName} in SOAP response");

            var serializer = new XmlSerializer(typeof(T), ns);
            using (var reader = new StringReader(node.OuterXml))
            {
                return (T)serializer.Deserialize(reader);
            }
        }

        public void Dispose()
        {
            _httpClient?.Dispose();
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackNotificationRequest
    {

        private WebAuthenticationDetail webAuthenticationDetailField;

        private ClientDetail clientDetailField;

        private TransactionDetail transactionDetailField;

        private VersionId versionField;

        private string trackingNumberField;

        private bool multiPieceField;

        private bool multiPieceFieldSpecified;

        private string pagingTokenField;

        private string trackingNumberUniqueIdField;

        private System.DateTime shipDateRangeBeginField;

        private bool shipDateRangeBeginFieldSpecified;

        private System.DateTime shipDateRangeEndField;

        private bool shipDateRangeEndFieldSpecified;

        private string senderEMailAddressField;

        private string senderContactNameField;

        private EMailNotificationDetail notificationDetailField;

        public WebAuthenticationDetail WebAuthenticationDetail { get { return this.webAuthenticationDetailField; } set { this.webAuthenticationDetailField = value; } }
        public ClientDetail ClientDetail { get { return this.clientDetailField; } set { this.clientDetailField = value; } }
        public TransactionDetail TransactionDetail { get { return this.transactionDetailField; } set { this.transactionDetailField = value; } }
        public VersionId Version { get { return this.versionField; } set { this.versionField = value; } }
        public string TrackingNumber { get { return this.trackingNumberField; } set { this.trackingNumberField = value; } }
        public bool MultiPiece { get { return this.multiPieceField; } set { this.multiPieceField = value; } }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool MultiPieceSpecified { get { return this.multiPieceFieldSpecified; } set { this.multiPieceFieldSpecified = value; } }
        public string PagingToken { get { return this.pagingTokenField; } set { this.pagingTokenField = value; } }
        public string TrackingNumberUniqueId { get { return this.trackingNumberUniqueIdField; } set { this.trackingNumberUniqueIdField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] public System.DateTime ShipDateRangeBegin { get { return this.shipDateRangeBeginField; } set { this.shipDateRangeBeginField = value; } }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ShipDateRangeBeginSpecified { get { return this.shipDateRangeBeginFieldSpecified; } set { this.shipDateRangeBeginFieldSpecified = value; } }
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] public System.DateTime ShipDateRangeEnd { get { return this.shipDateRangeEndField; } set { this.shipDateRangeEndField = value; } }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ShipDateRangeEndSpecified { get { return this.shipDateRangeEndFieldSpecified; } set { this.shipDateRangeEndFieldSpecified = value; } }
        public string SenderEMailAddress { get { return this.senderEMailAddressField; } set { this.senderEMailAddressField = value; } }
        public string SenderContactName { get { return this.senderContactNameField; } set { this.senderContactNameField = value; } }
        public EMailNotificationDetail NotificationDetail { get { return this.notificationDetailField; } set { this.notificationDetailField = value; } }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class WebAuthenticationDetail { public WebAuthenticationCredential UserCredential { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class WebAuthenticationCredential { public string Key { get; set; } public string Password { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class ClientDetail { public string AccountNumber { get; set; } public string MeterNumber { get; set; } public string IntegratorId { get; set; } public Localization Localization { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TransactionDetail { public string CustomerTransactionId { get; set; } public Localization Localization { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class Localization { public string LanguageCode { get; set; } public string LocaleCode { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class VersionId
    {
        public VersionId() { ServiceId = "trck"; Major = 5; Intermediate = 0; Minor = 0; }
        public string ServiceId { get; set; } public int Major { get; set; } public int Intermediate { get; set; } public int Minor { get; set; }
    }

    public enum NotificationSeverityType { ERROR, FAILURE, NOTE, SUCCESS, WARNING }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class Notification { public NotificationSeverityType Severity { get; set; } public string Source { get; set; } public string Code { get; set; } public string Message { get; set; } public string LocalizedMessage { get; set; } [System.Xml.Serialization.XmlElementAttribute("MessageParameters")] public NotificationParameter[] MessageParameters { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class NotificationParameter { public string Id { get; set; } public string Value { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackRequest
    {
        public WebAuthenticationDetail WebAuthenticationDetail { get; set; }
        public ClientDetail ClientDetail { get; set; }
        public TransactionDetail TransactionDetail { get; set; }
        public VersionId Version { get; set; }
        public CarrierCodeType CarrierCode { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool CarrierCodeSpecified { get; set; }
        public OperatingCompanyType OperatingCompany { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool OperatingCompanySpecified { get; set; }
        public TrackPackageIdentifier PackageIdentifier { get; set; }
        public string TrackingNumberUniqueIdentifier { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] public System.DateTime ShipDateRangeBegin { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ShipDateRangeBeginSpecified { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] public System.DateTime ShipDateRangeEnd { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ShipDateRangeEndSpecified { get; set; }
        public string ShipmentAccountNumber { get; set; }
        public Address Destination { get; set; }
        public bool IncludeDetailedScans { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool IncludeDetailedScansSpecified { get; set; }
        public string PagingToken { get; set; }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackReply
    {
        public NotificationSeverityType HighestSeverity { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("Notifications")] public Notification[] Notifications { get; set; }
        public TransactionDetail TransactionDetail { get; set; }
        public VersionId Version { get; set; }
        public bool DuplicateWaybill { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool DuplicateWaybillSpecified { get; set; }
        public bool MoreData { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool MoreDataSpecified { get; set; }
        public string PagingToken { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("TrackDetails")] public TrackDetail[] TrackDetails { get; set; }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackDetail
    {
        public Notification Notification { get; set; }
        public string TrackingNumber { get; set; }
        public string StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public string ServiceInfo { get; set; }
        public string PackageSequenceNumber { get; set; }
        public string PackageCount { get; set; }
        public Address ShipperAddress { get; set; }
        public Address DestinationAddress { get; set; }
        public System.DateTime EstimatedDeliveryTimestamp { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool EstimatedDeliveryTimestampSpecified { get; set; }
        public System.DateTime ActualDeliveryTimestamp { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ActualDeliveryTimestampSpecified { get; set; }
        public Address ActualDeliveryAddress { get; set; }
        public string DeliverySignatureName { get; set; }
        public bool SignatureProofOfDeliveryAvailable { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool SignatureProofOfDeliveryAvailableSpecified { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("Events")] public TrackEvent[] Events { get; set; }
        public System.DateTime ShipTimestamp { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ShipTimestampSpecified { get; set; }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackEvent
    {
        public System.DateTime Timestamp { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool TimestampSpecified { get; set; }
        public string EventType { get; set; }
        public string EventDescription { get; set; }
        public string StatusExceptionCode { get; set; }
        public string StatusExceptionDescription { get; set; }
        public Address Address { get; set; }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class Address
    {
        [System.Xml.Serialization.XmlElementAttribute("StreetLines")] public string[] StreetLines { get; set; }
        public string City { get; set; }
        public string StateOrProvinceCode { get; set; }
        public string PostalCode { get; set; }
        public string UrbanizationCode { get; set; }
        public string CountryCode { get; set; }
        public bool Residential { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool ResidentialSpecified { get; set; }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackPackageIdentifier { public string Value { get; set; } public TrackIdentifierType Type { get; set; } }

    public enum TrackIdentifierType { BILL_OF_LADING, COD_RETURN_TRACKING_NUMBER, CUSTOMER_AUTHORIZATION_NUMBER, CUSTOMER_REFERENCE, DEPARTMENT, FREE_FORM_REFERENCE, GROUND_INTERNATIONAL, GROUND_SHIPMENT_ID, GROUP_MPS, INVOICE, JOB_GLOBAL_TRACKING_NUMBER, ORDER_GLOBAL_TRACKING_NUMBER, ORDER_TO_PAY_NUMBER, PARTNER_CARRIER_NUMBER, PART_NUMBER, PURCHASE_ORDER, RETURNED_TO_SHIPPER_TRACKING_NUMBER, RETURN_MATERIALS_AUTHORIZATION, SHIPPER_REFERENCE, STANDARD_MPS, TRACKING_NUMBER_OR_DOORTAG, TRANSPORTATION_CONTROL_NUMBER }

    public enum CarrierCodeType { FDXC, FDXE, FDXG, FXCC, FXFR, FXSP }
    public enum OperatingCompanyType { FEDEX_OFFICE }

    public enum EMailNotificationEventType { ON_DELIVERY, ON_EXCEPTION, ON_SHIPMENT, ON_TENDER }
    public enum EMailNotificationRecipientType { BROKER, OTHER, RECIPIENT, SHIPPER }
    public enum EMailNotificationFormatType { HTML, TEXT, WIRELESS }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class EMailNotificationDetail { public string PersonalMessage { get; set; } [System.Xml.Serialization.XmlElementAttribute("Recipients")] public EMailNotificationRecipient[] Recipients { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class EMailNotificationRecipient { public EMailNotificationRecipientType EMailNotificationRecipientType { get; set; } [System.Xml.Serialization.XmlIgnoreAttribute()] public bool EMailNotificationRecipientTypeSpecified { get; set; } public string EMailAddress { get; set; } [System.Xml.Serialization.XmlElementAttribute("NotificationEventsRequested")] public EMailNotificationEventType[] NotificationEventsRequested { get; set; } public EMailNotificationFormatType Format { get; set; } public Localization Localization { get; set; } }

    // Remaining types preserved for compilation but simplified - used only by the tracking WSDL proxy
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class SignatureProofOfDeliveryLetterReply { public NotificationSeverityType HighestSeverity { get; set; } public Notification[] Notifications { get; set; } public TransactionDetail TransactionDetail { get; set; } public VersionId Version { get; set; } [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")] public byte[] Letter { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class SignatureProofOfDeliveryFaxReply { public NotificationSeverityType HighestSeverity { get; set; } public Notification[] Notifications { get; set; } public TransactionDetail TransactionDetail { get; set; } public VersionId Version { get; set; } public string FaxConfirmationNumber { get; set; } }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fedex.com/ws/track/v5")]
    public partial class TrackNotificationReply { public NotificationSeverityType HighestSeverity { get; set; } [System.Xml.Serialization.XmlElementAttribute("Notifications")] public Notification[] Notifications { get; set; } public TransactionDetail TransactionDetail { get; set; } public VersionId Version { get; set; } }
}
