//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Replaced SOAP web reference with HttpClient-based implementation for .NET 10.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Nop.Services.EuropaCheckVatService {
    using System;
    using System.ComponentModel;
    using System.Net.Http;
    using System.Threading.Tasks;
    using System.Xml.Linq;
    using System.Linq;
    using System.Xml.Serialization;

    /// <remarks/>
    public partial class checkVatService : IDisposable {
        
        private static readonly HttpClient _httpClient = new HttpClient();
        
        public string Url { get; set; }

        /// <remarks/>
        public checkVatService() {
            this.Url = global::Nop.Services.Properties.Settings.Default.Nop_Services_EuropaCheckVatService_checkVatService;
        }

        /// <remarks/>
        public event checkVatCompletedEventHandler checkVatCompleted;

        /// <remarks/>
        public event checkVatApproxCompletedEventHandler checkVatApproxCompleted;

        /// <remarks/>
        public System.DateTime checkVat(ref string countryCode, ref string vatNumber, out bool valid, out string name, out string address) {
            var soapEnvelope = string.Format(@"<soapenv:Envelope xmlns:soapenv=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:urn=""urn:ec.europa.eu:taxud:vies:services:checkVat:types"">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:checkVat>
         <urn:countryCode>{0}</urn:countryCode>
         <urn:vatNumber>{1}</urn:vatNumber>
      </urn:checkVat>
   </soapenv:Body>
</soapenv:Envelope>", System.Security.SecurityElement.Escape(countryCode), System.Security.SecurityElement.Escape(vatNumber));

            var content = new StringContent(soapEnvelope, System.Text.Encoding.UTF8, "text/xml");
            var response = _httpClient.PostAsync(this.Url, content).GetAwaiter().GetResult();
            var responseBody = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();

            var doc = XDocument.Parse(responseBody);
            XNamespace ns = "urn:ec.europa.eu:taxud:vies:services:checkVat:types";

            var checkVatResponse = doc.Descendants(ns + "checkVatResponse").FirstOrDefault();
            if (checkVatResponse == null) {
                throw new InvalidOperationException("Invalid VIES service response");
            }

            countryCode = checkVatResponse.Element(ns + "countryCode")?.Value ?? countryCode;
            vatNumber = checkVatResponse.Element(ns + "vatNumber")?.Value ?? vatNumber;
            valid = bool.TryParse(checkVatResponse.Element(ns + "valid")?.Value, out var v) && v;
            name = checkVatResponse.Element(ns + "name")?.Value;
            address = checkVatResponse.Element(ns + "address")?.Value;

            var dateStr = checkVatResponse.Element(ns + "requestDate")?.Value;
            return DateTime.TryParse(dateStr, out var dt) ? dt : DateTime.UtcNow;
        }

        /// <remarks/>
        public void checkVatAsync(string countryCode, string vatNumber) {
            this.checkVatAsync(countryCode, vatNumber, null);
        }

        /// <remarks/>
        public void checkVatAsync(string countryCode, string vatNumber, object userState) {
            Task.Run(() => {
                try {
                    string cc = countryCode;
                    string vn = vatNumber;
                    bool valid;
                    string name, address;
                    var result = this.checkVat(ref cc, ref vn, out valid, out name, out address);
                    this.checkVatCompleted?.Invoke(this, new checkVatCompletedEventArgs(
                        new object[] { result, cc, vn, valid, name, address }, null, false, userState));
                }
                catch (Exception ex) {
                    this.checkVatCompleted?.Invoke(this, new checkVatCompletedEventArgs(
                        null, ex, false, userState));
                }
            });
        }

        /// <remarks/>
        public System.DateTime checkVatApprox(
                    ref string countryCode,
                    ref string vatNumber,
                    ref string traderName,
                    ref string traderCompanyType,
                    ref string traderStreet,
                    ref string traderPostcode,
                    ref string traderCity,
                    string requesterCountryCode,
                    string requesterVatNumber,
                    out bool valid,
                    out string traderAddress,
                    out matchCode traderNameMatch,
                    out bool traderNameMatchSpecified,
                    out matchCode traderCompanyTypeMatch,
                    out bool traderCompanyTypeMatchSpecified,
                    out matchCode traderStreetMatch,
                    out bool traderStreetMatchSpecified,
                    out matchCode traderPostcodeMatch,
                    out bool traderPostcodeMatchSpecified,
                    out matchCode traderCityMatch,
                    out bool traderCityMatchSpecified,
                    out string requestIdentifier) {
            
            // checkVatApprox SOAP call
            var soapEnvelope = string.Format(@"<soapenv:Envelope xmlns:soapenv=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:urn=""urn:ec.europa.eu:taxud:vies:services:checkVat:types"">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:checkVatApprox>
         <urn:countryCode>{0}</urn:countryCode>
         <urn:vatNumber>{1}</urn:vatNumber>
         <urn:traderName>{2}</urn:traderName>
         <urn:traderCompanyType>{3}</urn:traderCompanyType>
         <urn:traderStreet>{4}</urn:traderStreet>
         <urn:traderPostcode>{5}</urn:traderPostcode>
         <urn:traderCity>{6}</urn:traderCity>
         <urn:requesterCountryCode>{7}</urn:requesterCountryCode>
         <urn:requesterVatNumber>{8}</urn:requesterVatNumber>
      </urn:checkVatApprox>
   </soapenv:Body>
</soapenv:Envelope>", 
                System.Security.SecurityElement.Escape(countryCode),
                System.Security.SecurityElement.Escape(vatNumber),
                System.Security.SecurityElement.Escape(traderName ?? ""),
                System.Security.SecurityElement.Escape(traderCompanyType ?? ""),
                System.Security.SecurityElement.Escape(traderStreet ?? ""),
                System.Security.SecurityElement.Escape(traderPostcode ?? ""),
                System.Security.SecurityElement.Escape(traderCity ?? ""),
                System.Security.SecurityElement.Escape(requesterCountryCode ?? ""),
                System.Security.SecurityElement.Escape(requesterVatNumber ?? ""));

            var content = new StringContent(soapEnvelope, System.Text.Encoding.UTF8, "text/xml");
            var response = _httpClient.PostAsync(this.Url, content).GetAwaiter().GetResult();
            var responseBody = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();

            var doc = XDocument.Parse(responseBody);
            XNamespace ns = "urn:ec.europa.eu:taxud:vies:services:checkVat:types";

            var resp = doc.Descendants(ns + "checkVatApproxResponse").FirstOrDefault();
            if (resp == null) {
                throw new InvalidOperationException("Invalid VIES service response");
            }

            countryCode = resp.Element(ns + "countryCode")?.Value ?? countryCode;
            vatNumber = resp.Element(ns + "vatNumber")?.Value ?? vatNumber;
            traderName = resp.Element(ns + "traderName")?.Value ?? traderName;
            traderCompanyType = resp.Element(ns + "traderCompanyType")?.Value ?? traderCompanyType;
            traderStreet = resp.Element(ns + "traderStreet")?.Value ?? traderStreet;
            traderPostcode = resp.Element(ns + "traderPostcode")?.Value ?? traderPostcode;
            traderCity = resp.Element(ns + "traderCity")?.Value ?? traderCity;
            valid = bool.TryParse(resp.Element(ns + "valid")?.Value, out var v) && v;
            traderAddress = resp.Element(ns + "traderAddress")?.Value;
            
            traderNameMatch = ParseMatchCode(resp.Element(ns + "traderNameMatch")?.Value, out traderNameMatchSpecified);
            traderCompanyTypeMatch = ParseMatchCode(resp.Element(ns + "traderCompanyTypeMatch")?.Value, out traderCompanyTypeMatchSpecified);
            traderStreetMatch = ParseMatchCode(resp.Element(ns + "traderStreetMatch")?.Value, out traderStreetMatchSpecified);
            traderPostcodeMatch = ParseMatchCode(resp.Element(ns + "traderPostcodeMatch")?.Value, out traderPostcodeMatchSpecified);
            traderCityMatch = ParseMatchCode(resp.Element(ns + "traderCityMatch")?.Value, out traderCityMatchSpecified);
            requestIdentifier = resp.Element(ns + "requestIdentifier")?.Value;

            var dateStr = resp.Element(ns + "requestDate")?.Value;
            return DateTime.TryParse(dateStr, out var dt) ? dt : DateTime.UtcNow;
        }

        private static matchCode ParseMatchCode(string value, out bool specified) {
            if (string.IsNullOrEmpty(value)) {
                specified = false;
                return matchCode.Item1;
            }
            specified = true;
            return value switch {
                "1" => matchCode.Item1,
                "2" => matchCode.Item2,
                "3" => matchCode.Item3,
                _ => matchCode.Item1
            };
        }

        /// <remarks/>
        public void checkVatApproxAsync(string countryCode, string vatNumber, string traderName, string traderCompanyType, string traderStreet, string traderPostcode, string traderCity, string requesterCountryCode, string requesterVatNumber) {
            this.checkVatApproxAsync(countryCode, vatNumber, traderName, traderCompanyType, traderStreet, traderPostcode, traderCity, requesterCountryCode, requesterVatNumber, null);
        }

        /// <remarks/>
        public void checkVatApproxAsync(string countryCode, string vatNumber, string traderName, string traderCompanyType, string traderStreet, string traderPostcode, string traderCity, string requesterCountryCode, string requesterVatNumber, object userState) {
            // Async not implemented - use sync version
            throw new NotImplementedException("Use synchronous checkVatApprox method instead");
        }

        /// <remarks/>
        public void CancelAsync(object userState) {
            // No-op for HttpClient-based implementation
        }

        public void Dispose() {
            // HttpClient is static, no disposal needed per instance
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:vies:services:checkVat:types")]
    public enum matchCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    public delegate void checkVatCompletedEventHandler(object sender, checkVatCompletedEventArgs e);
    
    /// <remarks/>
    public partial class checkVatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkVatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string vatNumber {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool valid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    public delegate void checkVatApproxCompletedEventHandler(object sender, checkVatApproxCompletedEventArgs e);
    
    /// <remarks/>
    public partial class checkVatApproxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkVatApproxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string vatNumber {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string traderName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string traderCompanyType {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string traderStreet {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string traderPostcode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string traderCity {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public bool valid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string traderAddress {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
        
        /// <remarks/>
        public matchCode traderNameMatch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((matchCode)(this.results[10]));
            }
        }
        
        /// <remarks/>
        public bool traderNameMatchSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[11]));
            }
        }
        
        /// <remarks/>
        public matchCode traderCompanyTypeMatch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((matchCode)(this.results[12]));
            }
        }
        
        /// <remarks/>
        public bool traderCompanyTypeMatchSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[13]));
            }
        }
        
        /// <remarks/>
        public matchCode traderStreetMatch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((matchCode)(this.results[14]));
            }
        }
        
        /// <remarks/>
        public bool traderStreetMatchSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[15]));
            }
        }
        
        /// <remarks/>
        public matchCode traderPostcodeMatch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((matchCode)(this.results[16]));
            }
        }
        
        /// <remarks/>
        public bool traderPostcodeMatchSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[17]));
            }
        }
        
        /// <remarks/>
        public matchCode traderCityMatch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((matchCode)(this.results[18]));
            }
        }
        
        /// <remarks/>
        public bool traderCityMatchSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[19]));
            }
        }
        
        /// <remarks/>
        public string requestIdentifier {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[20]));
            }
        }
    }
}

#pragma warning restore 1591
